### ISSUE TITLE
Plugin documentation

### ISSUE THREAD

**Issue by jackah2** [whimc/Observations#10]
`README.md` should be modified to contain more information about the plugin. For example, all commands with descriptions and all permissions.

Add JavaDocs to code.

**Comment by Geph** [comment]
@EmiCB @jackah2 I think this is done now isn't it?? Do we want more documentation on new functions?

**Comment by jackah2** [comment]
> @EmiCB @jackah2 I think this is done now isn't it?? Do we want more documentation on new functions?

Yeah this is technically done since all I specified was the README. I'll add on to it to include code documentation.
