### ISSUE TITLE
Hook into Quests to create a custom objective

### ISSUE THREAD

**Issue by jackah2** [whimc/Observations#12]
We should have a custom objective for when a player makes an observation. The [Quests API](https://github.com/PikaMug/Quests/wiki/Master-%E2%80%90-Custom-Quest-API) has the ability to do this. We should make sure the plugin still functions even if the server does not have Quests installed.

**Comment by pietelite** [comment]
Done in #14

**Comment by Geph** [comment]
Reminder to merge this in to new version?
