### ISSUE TITLE
Remove "Factual" observations, replace with "Ask a question"

### ISSUE THREAD

**Issue by Geph** [whimc/Observations#18]
Include stubs 
- what if ______ ?
- why ______?
- how ______ ?
- when ______ ?

**Comment by jackah2** [comment]
Since the questions will all be freehand, should it still require the permission? My thought is that clicking the prompt will directly open a sign for input.

**Comment by Geph** [comment]
Hrmm - well I was initially thinking we'd want to prime them with some structured examples (like "What if ______?" option: the moon were smaller, this earth spun slower, etc... "Why does _____ ?" or "How could _____?" ). We can probably put a permission on it to match open-ended prompts, if that makes your life easier to add it.
